function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // parentCharacter
	global.__objectDepths[1] = 0; // _PROJECTILE
	global.__objectDepths[2] = 0; // _SOLID
	global.__objectDepths[3] = -3; // _WEAPON
	global.__objectDepths[4] = 2; // objBlood
	global.__objectDepths[5] = 1; // objBreakableFragment
	global.__objectDepths[6] = 0; // objBreakableParent
	global.__objectDepths[7] = 0; // objEnvironmentalDebris
	global.__objectDepths[8] = 0; // objGib
	global.__objectDepths[9] = 0; // objVegetation
	global.__objectDepths[10] = 0; // objWater
	global.__objectDepths[11] = -4; // objEnemy
	global.__objectDepths[12] = 0; // objEnemyIdle
	global.__objectDepths[13] = -4; // objExecution
	global.__objectDepths[14] = 0; // objFurniture
	global.__objectDepths[15] = 0; // objSolid
	global.__objectDepths[16] = 0; // objWall
	global.__objectDepths[17] = 0; // objWindow
	global.__objectDepths[18] = -5; // objArrow
	global.__objectDepths[19] = 0; // objBeam
	global.__objectDepths[20] = 0; // objBlade
	global.__objectDepths[21] = -1002; // objBullet
	global.__objectDepths[22] = -1002; // objEBullet
	global.__objectDepths[23] = -1; // objC4
	global.__objectDepths[24] = -1002; // objFlame
	global.__objectDepths[25] = -1; // objGrenade
	global.__objectDepths[26] = -1; // objPierretteSMG
	global.__objectDepths[27] = -4; // objPetrolBomb
	global.__objectDepths[28] = -1; // objFlashbang
	global.__objectDepths[29] = -1; // objBouncyBall
	global.__objectDepths[30] = -5; // objGrenade40mm
	global.__objectDepths[31] = -4; // objLaser
	global.__objectDepths[32] = -5; // objNail
	global.__objectDepths[33] = -3; // objWeaponThrow
	global.__objectDepths[34] = 3; // objBrokenBottle
	global.__objectDepths[35] = 2; // objChemicalDebris
	global.__objectDepths[36] = 2; // objConcreteBlockBase
	global.__objectDepths[37] = 2; // objConcreteChunks
	global.__objectDepths[38] = 2; // objDebris
	global.__objectDepths[39] = 2; // objDebrisLarge
	global.__objectDepths[40] = -6; // objFlyingPapers
	global.__objectDepths[41] = 0; // objPlasticShard
	global.__objectDepths[42] = 2; // objShard
	global.__objectDepths[43] = 0; // objShatteredDoor
	global.__objectDepths[44] = 2; // objShell
	global.__objectDepths[45] = 0; // objTinyShard
	global.__objectDepths[46] = 3; // objTVBigParts
	global.__objectDepths[47] = 3; // objTVShards
	global.__objectDepths[48] = 2; // objDestroyedDoor
	global.__objectDepths[49] = 2; // objDiscardedGun
	global.__objectDepths[50] = 2; // objFootPrint
	global.__objectDepths[51] = 0; // obj_fd_rectangle
	global.__objectDepths[52] = -1000; // objChemicalSmoke
	global.__objectDepths[53] = -6; // objElectricFlare
	global.__objectDepths[54] = -6; // objElectricity
	global.__objectDepths[55] = -6; // objElectricSpark
	global.__objectDepths[56] = 4; // objExplosionGround
	global.__objectDepths[57] = -1003; // objFireBall
	global.__objectDepths[58] = -1003; // objFireBallFlame
	global.__objectDepths[59] = -3; // objPetrolBombExplosion
	global.__objectDepths[60] = -4; // objFirePuff
	global.__objectDepths[61] = -4; // objFireSpark
	global.__objectDepths[62] = -1000; // objFlameParticle
	global.__objectDepths[63] = -1003; // objFlameSmoke
	global.__objectDepths[64] = -1000; // objGrenadeExplosion
	global.__objectDepths[65] = -1005; // objFlashbangExplosion
	global.__objectDepths[66] = -1005; // objShockExplosion
	global.__objectDepths[67] = -6; // objSmokeExhale
	global.__objectDepths[68] = -67; // objSmokeHit
	global.__objectDepths[69] = -2; // objSmokePuffExplosion
	global.__objectDepths[70] = -7; // objSteam
	global.__objectDepths[71] = -1000; // objFireMedium
	global.__objectDepths[72] = -1005; // objTinyFire
	global.__objectDepths[73] = -1500; // objNuclearBomb
	global.__objectDepths[74] = 2; // objSmudge
	global.__objectDepths[75] = 2; // objTinyBlood
	global.__objectDepths[76] = 1; // objBloodSquirt
	global.__objectDepths[77] = 3; // objBigBlood
	global.__objectDepths[78] = 1; // objSplatter
	global.__objectDepths[79] = 2; // objSplat
	global.__objectDepths[80] = 4; // objBloodPool
	global.__objectDepths[81] = 1; // objSeveredHead
	global.__objectDepths[82] = 2; // objFleshChunk
	global.__objectDepths[83] = 1; // objBodyPart
	global.__objectDepths[84] = 2; // objBrains
	global.__objectDepths[85] = 2; // objBrainsSmall
	global.__objectDepths[86] = 2; // objFleshChunkLarge
	global.__objectDepths[87] = 2; // objIntestine
	global.__objectDepths[88] = 1; // objHeadPiece
	global.__objectDepths[89] = 2; // objHeadRipped
	global.__objectDepths[90] = 1; // objDeadBody
	global.__objectDepths[91] = 1; // objStunnedBody
	global.__objectDepths[92] = -1002; // objBlastImpact
	global.__objectDepths[93] = -120; // objBulletImpact
	global.__objectDepths[94] = -1002; // objCutImpact
	global.__objectDepths[95] = -1002; // objHitImpact
	global.__objectDepths[96] = -120; // objMultiSlashImpact
	global.__objectDepths[97] = -1002; // objSlashImpact
	global.__objectDepths[98] = -10000; // objExplosiveCircle
	global.__objectDepths[99] = 1; // objBeretta
	global.__objectDepths[100] = 1; // objCoin
	global.__objectDepths[101] = -16; // objCrow
	global.__objectDepths[102] = 3; // objFiles
	global.__objectDepths[103] = 3; // objFileSpreadFloor
	global.__objectDepths[104] = -6; // objFirefly
	global.__objectDepths[105] = -1002; // objFlare
	global.__objectDepths[106] = 1; // objGunClip
	global.__objectDepths[107] = -95; // objHouseLight
	global.__objectDepths[108] = -4; // objLaserParticle
	global.__objectDepths[109] = 1; // objMoney
	global.__objectDepths[110] = -998; // objPlayerDeathEffect
	global.__objectDepths[111] = -1003; // objPulseRipple
	global.__objectDepths[112] = -112; // objSeagull
	global.__objectDepths[113] = 0; // objShine
	global.__objectDepths[114] = -20; // objSpeedLine
	global.__objectDepths[115] = -1002; // objHealingEffect
	global.__objectDepths[116] = -5; // objBulletStream
	global.__objectDepths[117] = -1002; // objMuzzleFlash
	global.__objectDepths[118] = -10; // objMuzzleSmoke
	global.__objectDepths[119] = -4; // objPistolSmoke
	global.__objectDepths[120] = -101; // objRainbowPop
	global.__objectDepths[121] = 0; // objRainbowBurst
	global.__objectDepths[122] = -4; // objSmokePlume
	global.__objectDepths[123] = -6; // objDisruptorSmoke
	global.__objectDepths[124] = -1002; // objBlisteringSwords
	global.__objectDepths[125] = -3; // objDashEffect
	global.__objectDepths[126] = -1004; // objFlurrySlash
	global.__objectDepths[127] = -1010; // objPsychicCharged
	global.__objectDepths[128] = -1001; // objPsychicShield
	global.__objectDepths[129] = -1001; // objPsychicShieldBurst
	global.__objectDepths[130] = -1001; // objPsychicSlash
	global.__objectDepths[131] = -1002; // objPsychicSlashMassive
	global.__objectDepths[132] = -1004; // objPsychicSword
	global.__objectDepths[133] = -10005; // objRicochetingShot
	global.__objectDepths[134] = -20000; // objChromaticAberrationMenu
	global.__objectDepths[135] = 0; // objGodRays
	global.__objectDepths[136] = 0; // o_example
	global.__objectDepths[137] = 0; // o_magnifier
	global.__objectDepths[138] = 0; // o_magnifier_path
	global.__objectDepths[139] = 0; // o_shockwave
	global.__objectDepths[140] = -40; // objWarpEffect
	global.__objectDepths[141] = 1; // objAquariumBreak
	global.__objectDepths[142] = 3; // objAquariumWater
	global.__objectDepths[143] = 3; // objBigWater
	global.__objectDepths[144] = -10; // objBoilingWater
	global.__objectDepths[145] = 4; // objRainDrop
	global.__objectDepths[146] = 4; // objSplash
	global.__objectDepths[147] = -1000; // objWaterDrip
	global.__objectDepths[148] = 2; // objWaterPool
	global.__objectDepths[149] = 3; // objWaterPuddle
	global.__objectDepths[150] = 4; // objWaterRipple
	global.__objectDepths[151] = 3; // objWaterSmudge
	global.__objectDepths[152] = 1; // objWaterSplash
	global.__objectDepths[153] = 3; // objWaterSplat
	global.__objectDepths[154] = 0; // objWaterSteps
	global.__objectDepths[155] = 1003; // bgWaves
	global.__objectDepths[156] = 0; // objWavesH
	global.__objectDepths[157] = 0; // objWavesV
	global.__objectDepths[158] = 0; // objSnowEveningLight
	global.__objectDepths[159] = -887; // objSunlight
	global.__objectDepths[160] = -887; // objSunset
	global.__objectDepths[161] = 0; // objHeavyRain
	global.__objectDepths[162] = -100; // objLightRain
	global.__objectDepths[163] = -1000; // objRain
	global.__objectDepths[164] = 0; // objRainParentCollision
	global.__objectDepths[165] = -1000; // objSnow
	global.__objectDepths[166] = -1; // objKnockedOut
	global.__objectDepths[167] = -4; // objEnemyBurn
	global.__objectDepths[168] = 2; // objBurningBody
	global.__objectDepths[169] = 2; // objEDieBurn
	global.__objectDepths[170] = 0; // objEnemySpawner
	global.__objectDepths[171] = 3; // objMine
	global.__objectDepths[172] = -4; // objEnemyIdleDrink
	global.__objectDepths[173] = -4; // objEnemyIdleEatCandy
	global.__objectDepths[174] = -4; // objEnemyIdleGuard
	global.__objectDepths[175] = -4; // objEnemyIdleKnife
	global.__objectDepths[176] = -4; // objEnemyIdleYawn
	global.__objectDepths[177] = -4; // objEnemyIdleDrinkBeer
	global.__objectDepths[178] = -4; // objEnemyIdlePee
	global.__objectDepths[179] = -4; // objEnemyIdlePhone
	global.__objectDepths[180] = -4; // objEnemyIdleSmokeMelee
	global.__objectDepths[181] = -4; // objEnemyIdleSmokeSilencer
	global.__objectDepths[182] = -4; // objEnemyDodger
	global.__objectDepths[183] = -1; // objEnemyMeleePatrol
	global.__objectDepths[184] = -4; // objEnemyMeleeRandom
	global.__objectDepths[185] = -4; // objEnemyStaticMelee
	global.__objectDepths[186] = -4; // enemyPatrol
	global.__objectDepths[187] = -4; // enemyStatic
	global.__objectDepths[188] = -4; // enemyRandom
	global.__objectDepths[189] = -4; // enemyMeleeRandom
	global.__objectDepths[190] = -4; // obj_AIwander
	global.__objectDepths[191] = -4; // enemyCover
	global.__objectDepths[192] = -3; // objEnemyGiveUp
	global.__objectDepths[193] = -888; // efDesaturation
	global.__objectDepths[194] = -9999; // objConsole
	global.__objectDepths[195] = -10000; // objEffector
	global.__objectDepths[196] = -1000; // objGlareController
	global.__objectDepths[197] = 3; // objSurfacer
	global.__objectDepths[198] = 0; // WSOUND
	global.__objectDepths[199] = -100000; // efDirtyLens
	global.__objectDepths[200] = -10001; // objDrawRestart
	global.__objectDepths[201] = -10005; // objLevelComplete
	global.__objectDepths[202] = -1500; // objPoints
	global.__objectDepths[203] = -100000; // objThoughtFlash
	global.__objectDepths[204] = -100000; // objThoughtFlashDamaged
	global.__objectDepths[205] = -1010; // objDamageCounter
	global.__objectDepths[206] = -999; // iconExecution
	global.__objectDepths[207] = -1001; // objMainMenu
	global.__objectDepths[208] = 0; // objWave
	global.__objectDepths[209] = 0; // objBird
	global.__objectDepths[210] = 0; // objStar
	global.__objectDepths[211] = 0; // objSeaGlimmer
	global.__objectDepths[212] = 0; // objDisclaimer
	global.__objectDepths[213] = 0; // iElisabeth
	global.__objectDepths[214] = 0; // iFrancis
	global.__objectDepths[215] = 0; // iJohanna
	global.__objectDepths[216] = 0; // iJoseph
	global.__objectDepths[217] = 0; // iMiller
	global.__objectDepths[218] = 0; // iVeronika
	global.__objectDepths[219] = 0; // iAmy
	global.__objectDepths[220] = 0; // iDelilah
	global.__objectDepths[221] = 0; // iJohn
	global.__objectDepths[222] = 0; // iMariko
	global.__objectDepths[223] = 0; // iNicole
	global.__objectDepths[224] = 0; // iPierrette
	global.__objectDepths[225] = 0; // iSimone
	global.__objectDepths[226] = 0; // iThomas
	global.__objectDepths[227] = 0; // iYsolda
	global.__objectDepths[228] = 1; // mnCharacterSelect
	global.__objectDepths[229] = -5; // objLevelSelect
	global.__objectDepths[230] = -1000000; // objPause
	global.__objectDepths[231] = 0; // objPauseMenuSplatter
	global.__objectDepths[232] = 0; // objPauseMenuSplatterShot
	global.__objectDepths[233] = -100000; // mnPhone
	global.__objectDepths[234] = -999999; // objPhoneMessage
	global.__objectDepths[235] = 0; // objPhoneNotification
	global.__objectDepths[236] = 0; // objPhoneSendMail
	global.__objectDepths[237] = 0; // objDirtySink
	global.__objectDepths[238] = -1; // objDirtyToilet
	global.__objectDepths[239] = -1; // objHotelSuiteTub
	global.__objectDepths[240] = 4; // objShower
	global.__objectDepths[241] = -4; // objSink
	global.__objectDepths[242] = -4; // objLaundryMachine
	global.__objectDepths[243] = -4; // objBathroomSinks
	global.__objectDepths[244] = -1; // objToiletClean
	global.__objectDepths[245] = 1; // objTowelDisposal
	global.__objectDepths[246] = 3; // objTowels
	global.__objectDepths[247] = 0; // objTub
	global.__objectDepths[248] = 0; // objTubLawyer
	global.__objectDepths[249] = 0; // objUrinal
	global.__objectDepths[250] = -1; // objMakeupCabinet
	global.__objectDepths[251] = 0; // objBedFlannel
	global.__objectDepths[252] = -1; // objBed
	global.__objectDepths[253] = -1; // objBedFancy
	global.__objectDepths[254] = 1; // objArmChair
	global.__objectDepths[255] = -1; // objLeatherCouchLarge
	global.__objectDepths[256] = 0; // objCorporateCouch
	global.__objectDepths[257] = -1; // objCorporateSofaLong
	global.__objectDepths[258] = -2; // objCouchBeige
	global.__objectDepths[259] = 0; // objCouchCushion
	global.__objectDepths[260] = 3; // objCouchCushionGrey
	global.__objectDepths[261] = 0; // objCouchGrey
	global.__objectDepths[262] = 0; // objCouchLeatherBrown
	global.__objectDepths[263] = 0; // objCouchLong
	global.__objectDepths[264] = -2; // objCouchRipped
	global.__objectDepths[265] = 0; // objHospitalChair
	global.__objectDepths[266] = 0; // objJapaneseBench
	global.__objectDepths[267] = -1; // objLeatherArmchair
	global.__objectDepths[268] = 0; // objLeatherCouchAngled
	global.__objectDepths[269] = -1; // objLeatherCouchBlack
	global.__objectDepths[270] = -1; // objLeatherCouchL
	global.__objectDepths[271] = -1; // objLeatherCouchV
	global.__objectDepths[272] = 1; // objSaunaBench
	global.__objectDepths[273] = 0; // objBelltowerSofa
	global.__objectDepths[274] = -2; // objExplosiveBarrel
	global.__objectDepths[275] = -1; // objACUnit
	global.__objectDepths[276] = -5; // objAirDuct
	global.__objectDepths[277] = 0; // objBarrel
	global.__objectDepths[278] = -1; // objCementBags
	global.__objectDepths[279] = -1; // objChemicalLab
	global.__objectDepths[280] = -6; // objDrugMaterialShelf
	global.__objectDepths[281] = -5; // objGateLocked
	global.__objectDepths[282] = -1; // objGeneratorSmall
	global.__objectDepths[283] = -1; // objLabCounter
	global.__objectDepths[284] = -1; // objLabCounterBig
	global.__objectDepths[285] = -1; // objLabIsland
	global.__objectDepths[286] = 3; // objManholeNormal
	global.__objectDepths[287] = -14; // objPipeLarge
	global.__objectDepths[288] = -20; // objPipeSmall
	global.__objectDepths[289] = -2; // objPortableGenerator
	global.__objectDepths[290] = -15; // objPowerLines
	global.__objectDepths[291] = -10; // objRoofVent
	global.__objectDepths[292] = 3; // objSand
	global.__objectDepths[293] = 3; // objSewerVentilation
	global.__objectDepths[294] = -2; // objShippingCrateSmall
	global.__objectDepths[295] = -2; // objToolTable
	global.__objectDepths[296] = -1; // objTyre
	global.__objectDepths[297] = -1; // objWarehouseCargoBig
	global.__objectDepths[298] = -3; // objWarehouseCargoSmall
	global.__objectDepths[299] = -10; // objWarehouseShelvesBoxesH
	global.__objectDepths[300] = -11; // objWarehouseShelvesBoxesV
	global.__objectDepths[301] = -10; // objWarehouseShelves
	global.__objectDepths[302] = -20; // objWaterPipe
	global.__objectDepths[303] = -4; // objWaterSource
	global.__objectDepths[304] = -2; // objWoodenCrateLarge
	global.__objectDepths[305] = -2; // objWoodenCrateLong
	global.__objectDepths[306] = -2; // objWoodenCrateSmall
	global.__objectDepths[307] = -2; // objWorkTable
	global.__objectDepths[308] = -10; // objGarageDoor
	global.__objectDepths[309] = -1; // objChairPlastic
	global.__objectDepths[310] = -1; // objDrainageTub1
	global.__objectDepths[311] = -1; // objDrainageTub2
	global.__objectDepths[312] = -1; // objDrainageTub3
	global.__objectDepths[313] = 1; // objDrainageWaste
	global.__objectDepths[314] = 8; // objPlasticFloor
	global.__objectDepths[315] = 0; // objBuffetLine
	global.__objectDepths[316] = -2; // objBuffetPlates
	global.__objectDepths[317] = -1; // objCoffeeTable
	global.__objectDepths[318] = -1; // objCounter
	global.__objectDepths[319] = -3; // objDoubleFridge
	global.__objectDepths[320] = -1; // objDrinkTable
	global.__objectDepths[321] = -1; // objFoodCounter
	global.__objectDepths[322] = -3; // objFoodPreparationSupplies
	global.__objectDepths[323] = 0; // objFoodTray
	global.__objectDepths[324] = 0; // objFreezerSmall
	global.__objectDepths[325] = 0; // objIndustrialKitchen
	global.__objectDepths[326] = -2; // objKitchenCounter
	global.__objectDepths[327] = 0; // objKitchenCupboard
	global.__objectDepths[328] = 0; // objKitchenIsland
	global.__objectDepths[329] = -1; // objKitchenIslandMarble
	global.__objectDepths[330] = -1; // objKitchenSink
	global.__objectDepths[331] = -6; // objKitchenWood
	global.__objectDepths[332] = -2; // objMilitaryKitchen
	global.__objectDepths[333] = 0; // objMilitaryTrays
	global.__objectDepths[334] = -1; // objMinibar
	global.__objectDepths[335] = -3; // objWineRacks
	global.__objectDepths[336] = 2; // objPizza
	global.__objectDepths[337] = -6; // objSingleFridge
	global.__objectDepths[338] = 0; // objStove
	global.__objectDepths[339] = 0; // objStoveSmall
	global.__objectDepths[340] = 0; // objWashingMachine
	global.__objectDepths[341] = 0; // objWoodenKitchenIsland
	global.__objectDepths[342] = -5; // objKitchenAppliancesDark
	global.__objectDepths[343] = 3; // objAlcohol
	global.__objectDepths[344] = 0; // objBeerCooler
	global.__objectDepths[345] = 3; // objCigarettes
	global.__objectDepths[346] = -2; // objDrugCrate
	global.__objectDepths[347] = -2; // objMarijuanaBig
	global.__objectDepths[348] = -1; // objMarijuanaCrate
	global.__objectDepths[349] = 0; // objMarijuanaCrop
	global.__objectDepths[350] = -2; // objMarijuanaSmall
	global.__objectDepths[351] = 0; // objMarijuanaTable
	global.__objectDepths[352] = -1; // objBenchPress
	global.__objectDepths[353] = -5; // objPunchingBag
	global.__objectDepths[354] = -1; // objTreadMill
	global.__objectDepths[355] = -1; // objWeightRack
	global.__objectDepths[356] = 3; // objWeights
	global.__objectDepths[357] = 0; // objAquarium
	global.__objectDepths[358] = -1; // objBookshelfCheap
	global.__objectDepths[359] = -1; // objBurningTrashcan
	global.__objectDepths[360] = 0; // objBurntOutHoboFire
	global.__objectDepths[361] = 0; // objCandleTableBurning
	global.__objectDepths[362] = -1; // objCardboardBoxes
	global.__objectDepths[363] = -1; // objCardboardBoxOpened
	global.__objectDepths[364] = -48; // objChainFenceH
	global.__objectDepths[365] = 1; // objChair
	global.__objectDepths[366] = 1; // objSafeLarge
	global.__objectDepths[367] = -2; // objCleaningCart
	global.__objectDepths[368] = 0; // objClosetGrey
	global.__objectDepths[369] = -3; // objClosetHangerLong
	global.__objectDepths[370] = -6; // objClothesHanger
	global.__objectDepths[371] = -10; // objClothesHangerCircle
	global.__objectDepths[372] = -4; // objClothesline
	global.__objectDepths[373] = 3; // objDoorMatLawyer
	global.__objectDepths[374] = 3; // objDoormatTiny
	global.__objectDepths[375] = -3; // objDumpster
	global.__objectDepths[376] = -1; // objFirePlace
	global.__objectDepths[377] = 3; // objFormsFloor
	global.__objectDepths[378] = -10; // objFuseBox
	global.__objectDepths[379] = -1; // objGrandPiano
	global.__objectDepths[380] = -1; // objHearth
	global.__objectDepths[381] = 0; // objHearthBucket
	global.__objectDepths[382] = 0; // objHospitalBed
	global.__objectDepths[383] = 0; // objHotelClosetV
	global.__objectDepths[384] = 1; // objHotelFootStool
	global.__objectDepths[385] = 1; // objIrori
	global.__objectDepths[386] = -3; // objJanitorBucket
	global.__objectDepths[387] = -6; // objLamp
	global.__objectDepths[388] = -1; // objLaundryBasket
	global.__objectDepths[389] = -1; // objLuggage
	global.__objectDepths[390] = 0; // objMassageTableHotel
	global.__objectDepths[391] = 0; // objMassageTools
	global.__objectDepths[392] = -100; // objMetalDetector
	global.__objectDepths[393] = -1; // objMilkCarton
	global.__objectDepths[394] = -1; // objNewspaperStand
	global.__objectDepths[395] = -8; // objPaintingWallMetal
	global.__objectDepths[396] = -8; // objPaintingWallWood
	global.__objectDepths[397] = 3; // objPants
	global.__objectDepths[398] = 3; // objPaperFloorMess
	global.__objectDepths[399] = -3; // objPaperStack
	global.__objectDepths[400] = 3; // objPavementDrain
	global.__objectDepths[401] = -2; // objPhoneRecorder1
	global.__objectDepths[402] = -2; // objPhoneRecorder2
	global.__objectDepths[403] = 0; // objPorchBenchDecrepit
	global.__objectDepths[404] = 4; // objPuddle
	global.__objectDepths[405] = 0; // objRake
	global.__objectDepths[406] = 3; // objShirts
	global.__objectDepths[407] = 3; // objShoes
	global.__objectDepths[408] = -50; // objShojiH
	global.__objectDepths[409] = -52; // objShojiOpenH
	global.__objectDepths[410] = -52; // objShojiOpenV
	global.__objectDepths[411] = -50; // objShojiV
	global.__objectDepths[412] = 0; // objStreetLightBase
	global.__objectDepths[413] = 3; // objStyrofoam
	global.__objectDepths[414] = -2; // objSurveillanceBank
	global.__objectDepths[415] = -40; // objSurveillanceCamera
	global.__objectDepths[416] = -2; // objSurveillancePanel
	global.__objectDepths[417] = 1; // objTrashbag
	global.__objectDepths[418] = 0; // objTrashbagOpen
	global.__objectDepths[419] = 1; // objTrashbin
	global.__objectDepths[420] = 0; // objTrashBinLarge
	global.__objectDepths[421] = 0; // objTrashBinSquare
	global.__objectDepths[422] = 3; // objTrashFood
	global.__objectDepths[423] = -3; // objTVFlatScreen
	global.__objectDepths[424] = -3; // objTVFlatScreenLarge
	global.__objectDepths[425] = -6; // objTVWall
	global.__objectDepths[426] = 0; // objWaterCooler
	global.__objectDepths[427] = 0; // objWetFloorWarning
	global.__objectDepths[428] = 2; // objWetSpot
	global.__objectDepths[429] = 0; // objXray
	global.__objectDepths[430] = 1002; // objFrostedGlassPanel
	global.__objectDepths[431] = -1; // objShootingTarget
	global.__objectDepths[432] = 3; // objOrientalRug1
	global.__objectDepths[433] = 3; // objOrientalRug2
	global.__objectDepths[434] = 3; // objOrientalRug3
	global.__objectDepths[435] = -6; // objBookshelfWood
	global.__objectDepths[436] = 0; // objShelfWood
	global.__objectDepths[437] = 0; // objShelfWoodPapers
	global.__objectDepths[438] = 0; // objLocker
	global.__objectDepths[439] = 0; // objClosetWood
	global.__objectDepths[440] = -2; // objDataArchive
	global.__objectDepths[441] = 0; // objDataRecorder
	global.__objectDepths[442] = 0; // objBelltowerDeskLarge
	global.__objectDepths[443] = -2; // objBelltowerEntryDesk
	global.__objectDepths[444] = -2; // objBelltowerBigTable
	global.__objectDepths[445] = 0; // objDeskBase
	global.__objectDepths[446] = -1; // objFancyDesk
	global.__objectDepths[447] = 0; // objJunesRegister
	global.__objectDepths[448] = 0; // objKotatsu
	global.__objectDepths[449] = 0; // objLunchTable
	global.__objectDepths[450] = 1; // objLunchTableChair
	global.__objectDepths[451] = -2; // objLunchTableGang
	global.__objectDepths[452] = -1; // objLunchTableLongSpecial
	global.__objectDepths[453] = -1; // objLunchTableLongV
	global.__objectDepths[454] = 0; // objLunchTableSmall
	global.__objectDepths[455] = 1; // objMassageReception
	global.__objectDepths[456] = 0; // objMilitaryDiningTable
	global.__objectDepths[457] = 0; // objPhoneTable
	global.__objectDepths[458] = -1; // objBelltowerDeskH
	global.__objectDepths[459] = -1; // objBelltowerDeskV
	global.__objectDepths[460] = -1; // objSmallTable
	global.__objectDepths[461] = -1; // objDiningTableWood
	global.__objectDepths[462] = -2; // objSquareTableWood
	global.__objectDepths[463] = -3; // objTable
	global.__objectDepths[464] = -2; // objTableBroken
	global.__objectDepths[465] = -2; // objTableCircular
	global.__objectDepths[466] = -1; // objTableGambling
	global.__objectDepths[467] = 0; // objTableGang
	global.__objectDepths[468] = 0; // objTableGangMessy
	global.__objectDepths[469] = 0; // objTableSquareLight
	global.__objectDepths[470] = -1; // objTableGlass
	global.__objectDepths[471] = -1; // objTableTVWhite
	global.__objectDepths[472] = -4; // objMuleTruck
	global.__objectDepths[473] = -6; // objVanUnload
	global.__objectDepths[474] = -8; // objUtilityVan
	global.__objectDepths[475] = -6; // objPickupTruck
	global.__objectDepths[476] = -7; // objBushCorner
	global.__objectDepths[477] = 2; // objBushFlowers
	global.__objectDepths[478] = 3; // objBushLarge
	global.__objectDepths[479] = -7; // objBushSmall
	global.__objectDepths[480] = 3; // objBushSnowyLarge
	global.__objectDepths[481] = 2; // objBushSnowySmall
	global.__objectDepths[482] = -1; // objHedgeH
	global.__objectDepths[483] = -2; // objHedgeV
	global.__objectDepths[484] = -6; // objNaturalWaterfallSmall
	global.__objectDepths[485] = 0; // objPalmBroken
	global.__objectDepths[486] = -101; // objPalmDay
	global.__objectDepths[487] = -100; // objPalmNight
	global.__objectDepths[488] = 0; // objPalmTree
	global.__objectDepths[489] = -501; // objPalmTreeLarge
	global.__objectDepths[490] = -100; // objPalmTreeSmall
	global.__objectDepths[491] = -101; // objPlantDead
	global.__objectDepths[492] = 0; // objPlanter1
	global.__objectDepths[493] = -2; // objPlanter2
	global.__objectDepths[494] = -5; // objPlantHolderWall
	global.__objectDepths[495] = -2; // objPlantSmall
	global.__objectDepths[496] = 1; // objPlantSmallSnowy
	global.__objectDepths[497] = 1; // objPlantsNature
	global.__objectDepths[498] = -3; // objPlayerTree
	global.__objectDepths[499] = 3; // objRocks
	global.__objectDepths[500] = 2; // objSakuraPetalsGround
	global.__objectDepths[501] = 2; // objLeavesScattered
	global.__objectDepths[502] = -150; // objSakuraSmall
	global.__objectDepths[503] = -150; // objSakuraTree
	global.__objectDepths[504] = -50; // objTreeDead
	global.__objectDepths[505] = -500; // objTreeForestNight
	global.__objectDepths[506] = -500; // objTreeForestNormal
	global.__objectDepths[507] = -200; // objTreeForestSnowy
	global.__objectDepths[508] = -600; // objTreeMassive
	global.__objectDepths[509] = -105; // objTreeNormal
	global.__objectDepths[510] = -3; // objTreePot
	global.__objectDepths[511] = -100; // objTreeSmall
	global.__objectDepths[512] = -40; // objWoodenTrellis
	global.__objectDepths[513] = -49; // objWoodenTrellisLong
	global.__objectDepths[514] = 1001; // objDirtRoad
	global.__objectDepths[515] = -5; // objFirePit
	global.__objectDepths[516] = 0; // objLog
	global.__objectDepths[517] = -3; // objBarbedWire
	global.__objectDepths[518] = -1; // objTent
	global.__objectDepths[519] = -1; // objHose
	global.__objectDepths[520] = 10; // objRiverFrozen
	global.__objectDepths[521] = 0; // objBarBooth
	global.__objectDepths[522] = -1; // objBarFancy
	global.__objectDepths[523] = -1; // objBarFancySmall
	global.__objectDepths[524] = -30; // objBarLights
	global.__objectDepths[525] = 0; // objBarRegister
	global.__objectDepths[526] = 0; // objBarShelf
	global.__objectDepths[527] = -1; // objBarShelfWood
	global.__objectDepths[528] = 0; // objBarSmallBlack
	global.__objectDepths[529] = 0; // objBarStage
	global.__objectDepths[530] = 1; // objBarStoolBlack
	global.__objectDepths[531] = 1; // objBarStoolEquinox
	global.__objectDepths[532] = 1; // objBarStoolLeather
	global.__objectDepths[533] = 1; // objBarStoolWhite
	global.__objectDepths[534] = 0; // objBarTableBlack
	global.__objectDepths[535] = 0; // objBarTableWood
	global.__objectDepths[536] = -2; // objBarWood
	global.__objectDepths[537] = -2; // objBarShelfWoodLong
	global.__objectDepths[538] = 0; // objDinerBuffet
	global.__objectDepths[539] = 0; // objDinerChair
	global.__objectDepths[540] = -1; // objDinerCoffeeTable
	global.__objectDepths[541] = -2; // objDinerCounterLarge
	global.__objectDepths[542] = -3; // objDinerCup
	global.__objectDepths[543] = -3; // objDinerFoodCounter
	global.__objectDepths[544] = 0; // objDinerGrill
	global.__objectDepths[545] = 1; // objDinerSink
	global.__objectDepths[546] = -1; // objDinerSodaFountain
	global.__objectDepths[547] = 0; // objDinerTable
	global.__objectDepths[548] = -50; // objDinerWindowH
	global.__objectDepths[549] = -50; // objDinerWindowV
	global.__objectDepths[550] = -105; // objBannerV
	global.__objectDepths[551] = 0; // objBeadedArmchair
	global.__objectDepths[552] = -2; // objBonsaiTreeLarge
	global.__objectDepths[553] = 0; // objBuddha
	global.__objectDepths[554] = 0; // objChineseBar
	global.__objectDepths[555] = 0; // objChineseBarShelf
	global.__objectDepths[556] = 0; // objChineseFishtank
	global.__objectDepths[557] = 0; // objChineseFoodDisplay
	global.__objectDepths[558] = -10; // objChineseLightBlue
	global.__objectDepths[559] = -10; // objChineseLightOrange
	global.__objectDepths[560] = -10; // objChineseLightPink
	global.__objectDepths[561] = -10; // objChineseLightRed
	global.__objectDepths[562] = 0; // objChinesePlantSmall
	global.__objectDepths[563] = -2; // objChineseStatue
	global.__objectDepths[564] = 0; // objFoodPrepTable
	global.__objectDepths[565] = 0; // objFryingKitchen
	global.__objectDepths[566] = 0; // objGoldenCat
	global.__objectDepths[567] = 0; // objGoldenDragon
	global.__objectDepths[568] = 0; // objGunsmithDesk
	global.__objectDepths[569] = 1; // objHighballSign
	global.__objectDepths[570] = -1; // objKitchenBenchGunsmith
	global.__objectDepths[571] = -10; // objKitchenLightQuad
	global.__objectDepths[572] = 0; // objNoodleTableH
	global.__objectDepths[573] = -3; // objPantherStatue
	global.__objectDepths[574] = 0; // objRailBar
	global.__objectDepths[575] = -1; // objRegisterBrown
	global.__objectDepths[576] = -2; // objTableGunSmith
	global.__objectDepths[577] = 3; // objTargetPractice
	global.__objectDepths[578] = 0; // objTVParty1
	global.__objectDepths[579] = 0; // objTVParty3
	global.__objectDepths[580] = 0; // objWokKitchen
	global.__objectDepths[581] = 1001; // objMetroCarScene
	global.__objectDepths[582] = -50; // objMetroCarWall
	global.__objectDepths[583] = -50; // objMetroCarWindowH
	global.__objectDepths[584] = -7; // objMetroLeanHandle
	global.__objectDepths[585] = 1; // objMetroSeatsDouble
	global.__objectDepths[586] = 0; // objMetroSeatsLine
	global.__objectDepths[587] = -7; // objMetroStandHandleDown
	global.__objectDepths[588] = -7; // objMetroStandHandleUp
	global.__objectDepths[589] = 0; // objSubwayBenchH
	global.__objectDepths[590] = 0; // objSubwayBenchV
	global.__objectDepths[591] = -8; // objSubwayBillboard
	global.__objectDepths[592] = -3; // objSubwayDoor
	global.__objectDepths[593] = 0; // objSubwayGate
	global.__objectDepths[594] = -5; // objSubwayGateLocked
	global.__objectDepths[595] = -100; // objSubwayLight
	global.__objectDepths[596] = -300; // objSubwayLightV
	global.__objectDepths[597] = 0; // objSubwayMap
	global.__objectDepths[598] = -10; // objSubwayPole
	global.__objectDepths[599] = -1; // objSubwayReception
	global.__objectDepths[600] = -8; // objSubwayTimeDisplay
	global.__objectDepths[601] = -2; // objExecutiveTable
	global.__objectDepths[602] = -3; // objComputerMonitor
	global.__objectDepths[603] = 3; // objComputerParts
	global.__objectDepths[604] = 3; // objComputerPartsBig
	global.__objectDepths[605] = 0; // objConferenceTableDark
	global.__objectDepths[606] = 0; // objConferenceTableLight
	global.__objectDepths[607] = -1; // objCopyMachine
	global.__objectDepths[608] = -80; // objCorporateDoors
	global.__objectDepths[609] = -1; // objCorporateReceptionLight
	global.__objectDepths[610] = -2; // objFileCabinet
	global.__objectDepths[611] = -3; // objLaptop
	global.__objectDepths[612] = -1; // objModernArt
	global.__objectDepths[613] = 0; // objOfficeBarMassive
	global.__objectDepths[614] = 0; // objOfficeDrapes
	global.__objectDepths[615] = 0; // objOfficeFountainLarge
	global.__objectDepths[616] = 0; // objOfficeFountainMedium
	global.__objectDepths[617] = 0; // objOfficeFountainSmall1
	global.__objectDepths[618] = 0; // objOfficeFountainSmall2
	global.__objectDepths[619] = -10; // objOfficePlant
	global.__objectDepths[620] = -5; // objOfficePlantSmall
	global.__objectDepths[621] = 0; // objOfficeReceptionTable
	global.__objectDepths[622] = 0; // objOfficeTableBig
	global.__objectDepths[623] = 0; // objOfficeTableCircular
	global.__objectDepths[624] = 0; // objOfficeTableSmall
	global.__objectDepths[625] = 1; // objRollingChairOffice
	global.__objectDepths[626] = 1; // objRollingChairPolice
	global.__objectDepths[627] = -7; // objWhiteBoard
	global.__objectDepths[628] = 1; // objWhiteBoardLarge
	global.__objectDepths[629] = 1; // objBoardwalkOcean
	global.__objectDepths[630] = 0; // objCreateWater
	global.__objectDepths[631] = 13; // objFishWater
	global.__objectDepths[632] = 11; // objLeafWater
	global.__objectDepths[633] = -999; // objOceanFog
	global.__objectDepths[634] = -3; // objRailV
	global.__objectDepths[635] = 0; // objRippleLake
	global.__objectDepths[636] = 100; // objWaterSurface
	global.__objectDepths[637] = 1004; // objWaterTile
	global.__objectDepths[638] = -3; // objWoodenBench
	global.__objectDepths[639] = -1; // objBoatBridge
	global.__objectDepths[640] = 8; // objBoatPool
	global.__objectDepths[641] = -1; // objLifePreserver
	global.__objectDepths[642] = 0; // objSunchair
	global.__objectDepths[643] = -6; // objParasol
	global.__objectDepths[644] = -1; // objCommsTable
	global.__objectDepths[645] = -2; // objAmmoBox
	global.__objectDepths[646] = -1; // objSupplyBox
	global.__objectDepths[647] = -3; // objWeaponSpawn
	global.__objectDepths[648] = -2; // objAxeWall
	global.__objectDepths[649] = -3; // objGrenadeSpawn
	global.__objectDepths[650] = -5; // objKatanaWall
	global.__objectDepths[651] = -2; // objToolbox
	global.__objectDepths[652] = -5; // objUtilityClosetMetal
	global.__objectDepths[653] = -1005; // objVendingMachine
	global.__objectDepths[654] = -1; // objSodaCan
	global.__objectDepths[655] = -10; // objLightBarOrange
	global.__objectDepths[656] = -10; // objLightBarWhite
	global.__objectDepths[657] = -10; // objNeonSignRed
	global.__objectDepths[658] = -10; // objOfficeLightDown
	global.__objectDepths[659] = -10; // objOfficeLightLeft
	global.__objectDepths[660] = -10; // objOfficeLightRight
	global.__objectDepths[661] = -10; // objOfficeLightUp
	global.__objectDepths[662] = -5; // objStreetLight
	global.__objectDepths[663] = -10; // objWallLamp
	global.__objectDepths[664] = -10; // objStreetLightWhite
	global.__objectDepths[665] = 1; // objFloorLamp
	global.__objectDepths[666] = -10; // objStreetLampAmber
	global.__objectDepths[667] = -10000; // objLFGlowOrange
	global.__objectDepths[668] = -1000000; // objLFTailOrange
	global.__objectDepths[669] = 0; // objLightMonitor
	global.__objectDepths[670] = 0; // objLightTV
	global.__objectDepths[671] = 0; // objMetroLight
	global.__objectDepths[672] = 0; // objMuzzleLight
	global.__objectDepths[673] = 0; // objVMAqua
	global.__objectDepths[674] = 0; // objVMGreen
	global.__objectDepths[675] = 0; // objVMOrange
	global.__objectDepths[676] = 0; // objVMPink
	global.__objectDepths[677] = -4; // objSAWhite
	global.__objectDepths[678] = 0; // objSAAmber
	global.__objectDepths[679] = 0; // objSAGreen
	global.__objectDepths[680] = 0; // objSAOrange
	global.__objectDepths[681] = 0; // objSAPink
	global.__objectDepths[682] = 0; // objSARed
	global.__objectDepths[683] = 0; // objSAAqua
	global.__objectDepths[684] = -2; // objPlayerCar
	global.__objectDepths[685] = 2; // objPlayerCarFloor
	global.__objectDepths[686] = -7; // objPlayerCarRoof
	global.__objectDepths[687] = -3; // objPlayerCarTrunk
	global.__objectDepths[688] = -1; // objPlayerCarTrunkInterior
	global.__objectDepths[689] = -4; // objPAttackKnee
	global.__objectDepths[690] = -4; // objPAttackThroat
	global.__objectDepths[691] = -2; // objPAxeKill
	global.__objectDepths[692] = -2; // objPBluntKill
	global.__objectDepths[693] = 0; // objPBoilingPotKill
	global.__objectDepths[694] = -2; // objPBottleBrokenKill
	global.__objectDepths[695] = -2; // objPBottleKill
	global.__objectDepths[696] = -2; // objPBrickKill
	global.__objectDepths[697] = 0; // objPBrokenPoolKill
	global.__objectDepths[698] = -2; // objPChainsawKill1
	global.__objectDepths[699] = -2; // objPChainsawKill2
	global.__objectDepths[700] = -2; // objPDrillKill
	global.__objectDepths[701] = -2; // objPKill9mm
	global.__objectDepths[702] = -2; // objPKillAJM
	global.__objectDepths[703] = -2; // objPKillAK
	global.__objectDepths[704] = -2; // objPKillBeretta
	global.__objectDepths[705] = -2; // objPKillChainsawLean
	global.__objectDepths[706] = -2; // objPKillCleaver
	global.__objectDepths[707] = -2; // objPKillClub
	global.__objectDepths[708] = -2; // objPKillDesertEagle
	global.__objectDepths[709] = -2; // objPKillFAL
	global.__objectDepths[710] = -2; // objPKillFAMAE
	global.__objectDepths[711] = -4; // objPKillFat
	global.__objectDepths[712] = -2; // objPKillHammer
	global.__objectDepths[713] = -2; // objPKillHeadRip
	global.__objectDepths[714] = -2; // objPKillHK417
	global.__objectDepths[715] = -2; // objPKillIngram
	global.__objectDepths[716] = -2; // objPKillKatana
	global.__objectDepths[717] = 0; // objPKillKitchenKnife
	global.__objectDepths[718] = -2; // objPKillKnife
	global.__objectDepths[719] = -2; // objPKillKnifeStab
	global.__objectDepths[720] = -4; // objPKillLean
	global.__objectDepths[721] = -4; // objPKillLeanNonlethal
	global.__objectDepths[722] = -2; // objPKillMachete
	global.__objectDepths[723] = -2; // objPKillMacheteSlash
	global.__objectDepths[724] = -2; // objPKillMagnum
	global.__objectDepths[725] = -2; // objPKillMP5
	global.__objectDepths[726] = -2; // objPKillNailgun
	global.__objectDepths[727] = -2; // objPKillNeckSnap
	global.__objectDepths[728] = 0; // objPKillP90
	global.__objectDepths[729] = 0; // objPKillPipe
	global.__objectDepths[730] = -2; // objPKillPunch
	global.__objectDepths[731] = -2; // objPKillShotgun
	global.__objectDepths[732] = -2; // objPKillSilencer
	global.__objectDepths[733] = -2; // objPKillStomp
	global.__objectDepths[734] = -2; // objPKillThompson
	global.__objectDepths[735] = -2; // objPKillUzi
	global.__objectDepths[736] = -2; // objPKillWrench
	global.__objectDepths[737] = -2; // objPMercyKillSnap
	global.__objectDepths[738] = -2; // objPMercyKillStomp
	global.__objectDepths[739] = -2; // objPPoolKill
	global.__objectDepths[740] = -2; // objPScrewdriverKill
	global.__objectDepths[741] = -2; // objPSkateboardKill
	global.__objectDepths[742] = -2; // objPSledgeKill
	global.__objectDepths[743] = -4; // objThomasAttackKnee
	global.__objectDepths[744] = -100; // objPlayerDead
	global.__objectDepths[745] = -4; // objPlayer
	global.__objectDepths[746] = -3; // objHealthPickup
	global.__objectDepths[747] = -20; // maskShield
	global.__objectDepths[748] = -3; // objPierretteShield
	global.__objectDepths[749] = -10; // objDoorH
	global.__objectDepths[750] = -10; // objDoorH2
	global.__objectDepths[751] = -10; // objDoorV
	global.__objectDepths[752] = -10; // objDoorV2
	global.__objectDepths[753] = -10; // objSlidingDoorH
	global.__objectDepths[754] = -20; // objSlidingDoorsDoubleH
	global.__objectDepths[755] = -1; // objSlidingDoorsDoubleV
	global.__objectDepths[756] = -10; // objSlidingDoorV
	global.__objectDepths[757] = -49; // objCorporateDoorsH
	global.__objectDepths[758] = -150; // objTeleporter
	global.__objectDepths[759] = -50; // objConcreteBlock
	global.__objectDepths[760] = -51; // objWallBrickH
	global.__objectDepths[761] = -50; // objWallBrickV
	global.__objectDepths[762] = -50; // objWallHeavyV
	global.__objectDepths[763] = -50; // objWallHeavyH
	global.__objectDepths[764] = -50; // objWallCorner
	global.__objectDepths[765] = -50; // objWallWoodH
	global.__objectDepths[766] = -50; // objWallWoodV
	global.__objectDepths[767] = -3; // objFenceV
	global.__objectDepths[768] = -3; // objFenceH
	global.__objectDepths[769] = -999; // objInvisibleBoundary
	global.__objectDepths[770] = -49; // objRenovationWallH
	global.__objectDepths[771] = -49; // objRenovationWallV
	global.__objectDepths[772] = -50; // objBrokenWindowH
	global.__objectDepths[773] = -50; // objBrokenWindowV
	global.__objectDepths[774] = -50; // objGlassPanelH
	global.__objectDepths[775] = -50; // objGlassPanelHBroken
	global.__objectDepths[776] = -50; // objGlassPanelV
	global.__objectDepths[777] = -50; // objGlassPanelVBroken
	global.__objectDepths[778] = -20; // objWallWindow
	global.__objectDepths[779] = -50; // objWindowH
	global.__objectDepths[780] = -50; // objWindowV
	global.__objectDepths[781] = 0; // objWindowExplodeH
	global.__objectDepths[782] = 0; // objWindowExplodeV
	global.__objectDepths[783] = -50; // objGlassWall


	global.__objectNames[0] = "parentCharacter";
	global.__objectNames[1] = "_PROJECTILE";
	global.__objectNames[2] = "_SOLID";
	global.__objectNames[3] = "_WEAPON";
	global.__objectNames[4] = "objBlood";
	global.__objectNames[5] = "objBreakableFragment";
	global.__objectNames[6] = "objBreakableParent";
	global.__objectNames[7] = "objEnvironmentalDebris";
	global.__objectNames[8] = "objGib";
	global.__objectNames[9] = "objVegetation";
	global.__objectNames[10] = "objWater";
	global.__objectNames[11] = "objEnemy";
	global.__objectNames[12] = "objEnemyIdle";
	global.__objectNames[13] = "objExecution";
	global.__objectNames[14] = "objFurniture";
	global.__objectNames[15] = "objSolid";
	global.__objectNames[16] = "objWall";
	global.__objectNames[17] = "objWindow";
	global.__objectNames[18] = "objArrow";
	global.__objectNames[19] = "objBeam";
	global.__objectNames[20] = "objBlade";
	global.__objectNames[21] = "objBullet";
	global.__objectNames[22] = "objEBullet";
	global.__objectNames[23] = "objC4";
	global.__objectNames[24] = "objFlame";
	global.__objectNames[25] = "objGrenade";
	global.__objectNames[26] = "objPierretteSMG";
	global.__objectNames[27] = "objPetrolBomb";
	global.__objectNames[28] = "objFlashbang";
	global.__objectNames[29] = "objBouncyBall";
	global.__objectNames[30] = "objGrenade40mm";
	global.__objectNames[31] = "objLaser";
	global.__objectNames[32] = "objNail";
	global.__objectNames[33] = "objWeaponThrow";
	global.__objectNames[34] = "objBrokenBottle";
	global.__objectNames[35] = "objChemicalDebris";
	global.__objectNames[36] = "objConcreteBlockBase";
	global.__objectNames[37] = "objConcreteChunks";
	global.__objectNames[38] = "objDebris";
	global.__objectNames[39] = "objDebrisLarge";
	global.__objectNames[40] = "objFlyingPapers";
	global.__objectNames[41] = "objPlasticShard";
	global.__objectNames[42] = "objShard";
	global.__objectNames[43] = "objShatteredDoor";
	global.__objectNames[44] = "objShell";
	global.__objectNames[45] = "objTinyShard";
	global.__objectNames[46] = "objTVBigParts";
	global.__objectNames[47] = "objTVShards";
	global.__objectNames[48] = "objDestroyedDoor";
	global.__objectNames[49] = "objDiscardedGun";
	global.__objectNames[50] = "objFootPrint";
	global.__objectNames[51] = "obj_fd_rectangle";
	global.__objectNames[52] = "objChemicalSmoke";
	global.__objectNames[53] = "objElectricFlare";
	global.__objectNames[54] = "objElectricity";
	global.__objectNames[55] = "objElectricSpark";
	global.__objectNames[56] = "objExplosionGround";
	global.__objectNames[57] = "objFireBall";
	global.__objectNames[58] = "objFireBallFlame";
	global.__objectNames[59] = "objPetrolBombExplosion";
	global.__objectNames[60] = "objFirePuff";
	global.__objectNames[61] = "objFireSpark";
	global.__objectNames[62] = "objFlameParticle";
	global.__objectNames[63] = "objFlameSmoke";
	global.__objectNames[64] = "objGrenadeExplosion";
	global.__objectNames[65] = "objFlashbangExplosion";
	global.__objectNames[66] = "objShockExplosion";
	global.__objectNames[67] = "objSmokeExhale";
	global.__objectNames[68] = "objSmokeHit";
	global.__objectNames[69] = "objSmokePuffExplosion";
	global.__objectNames[70] = "objSteam";
	global.__objectNames[71] = "objFireMedium";
	global.__objectNames[72] = "objTinyFire";
	global.__objectNames[73] = "objNuclearBomb";
	global.__objectNames[74] = "objSmudge";
	global.__objectNames[75] = "objTinyBlood";
	global.__objectNames[76] = "objBloodSquirt";
	global.__objectNames[77] = "objBigBlood";
	global.__objectNames[78] = "objSplatter";
	global.__objectNames[79] = "objSplat";
	global.__objectNames[80] = "objBloodPool";
	global.__objectNames[81] = "objSeveredHead";
	global.__objectNames[82] = "objFleshChunk";
	global.__objectNames[83] = "objBodyPart";
	global.__objectNames[84] = "objBrains";
	global.__objectNames[85] = "objBrainsSmall";
	global.__objectNames[86] = "objFleshChunkLarge";
	global.__objectNames[87] = "objIntestine";
	global.__objectNames[88] = "objHeadPiece";
	global.__objectNames[89] = "objHeadRipped";
	global.__objectNames[90] = "objDeadBody";
	global.__objectNames[91] = "objStunnedBody";
	global.__objectNames[92] = "objBlastImpact";
	global.__objectNames[93] = "objBulletImpact";
	global.__objectNames[94] = "objCutImpact";
	global.__objectNames[95] = "objHitImpact";
	global.__objectNames[96] = "objMultiSlashImpact";
	global.__objectNames[97] = "objSlashImpact";
	global.__objectNames[98] = "objExplosiveCircle";
	global.__objectNames[99] = "objBeretta";
	global.__objectNames[100] = "objCoin";
	global.__objectNames[101] = "objCrow";
	global.__objectNames[102] = "objFiles";
	global.__objectNames[103] = "objFileSpreadFloor";
	global.__objectNames[104] = "objFirefly";
	global.__objectNames[105] = "objFlare";
	global.__objectNames[106] = "objGunClip";
	global.__objectNames[107] = "objHouseLight";
	global.__objectNames[108] = "objLaserParticle";
	global.__objectNames[109] = "objMoney";
	global.__objectNames[110] = "objPlayerDeathEffect";
	global.__objectNames[111] = "objPulseRipple";
	global.__objectNames[112] = "objSeagull";
	global.__objectNames[113] = "objShine";
	global.__objectNames[114] = "objSpeedLine";
	global.__objectNames[115] = "objHealingEffect";
	global.__objectNames[116] = "objBulletStream";
	global.__objectNames[117] = "objMuzzleFlash";
	global.__objectNames[118] = "objMuzzleSmoke";
	global.__objectNames[119] = "objPistolSmoke";
	global.__objectNames[120] = "objRainbowPop";
	global.__objectNames[121] = "objRainbowBurst";
	global.__objectNames[122] = "objSmokePlume";
	global.__objectNames[123] = "objDisruptorSmoke";
	global.__objectNames[124] = "objBlisteringSwords";
	global.__objectNames[125] = "objDashEffect";
	global.__objectNames[126] = "objFlurrySlash";
	global.__objectNames[127] = "objPsychicCharged";
	global.__objectNames[128] = "objPsychicShield";
	global.__objectNames[129] = "objPsychicShieldBurst";
	global.__objectNames[130] = "objPsychicSlash";
	global.__objectNames[131] = "objPsychicSlashMassive";
	global.__objectNames[132] = "objPsychicSword";
	global.__objectNames[133] = "objRicochetingShot";
	global.__objectNames[134] = "objChromaticAberrationMenu";
	global.__objectNames[135] = "objGodRays";
	global.__objectNames[136] = "o_example";
	global.__objectNames[137] = "o_magnifier";
	global.__objectNames[138] = "o_magnifier_path";
	global.__objectNames[139] = "o_shockwave";
	global.__objectNames[140] = "objWarpEffect";
	global.__objectNames[141] = "objAquariumBreak";
	global.__objectNames[142] = "objAquariumWater";
	global.__objectNames[143] = "objBigWater";
	global.__objectNames[144] = "objBoilingWater";
	global.__objectNames[145] = "objRainDrop";
	global.__objectNames[146] = "objSplash";
	global.__objectNames[147] = "objWaterDrip";
	global.__objectNames[148] = "objWaterPool";
	global.__objectNames[149] = "objWaterPuddle";
	global.__objectNames[150] = "objWaterRipple";
	global.__objectNames[151] = "objWaterSmudge";
	global.__objectNames[152] = "objWaterSplash";
	global.__objectNames[153] = "objWaterSplat";
	global.__objectNames[154] = "objWaterSteps";
	global.__objectNames[155] = "bgWaves";
	global.__objectNames[156] = "objWavesH";
	global.__objectNames[157] = "objWavesV";
	global.__objectNames[158] = "objSnowEveningLight";
	global.__objectNames[159] = "objSunlight";
	global.__objectNames[160] = "objSunset";
	global.__objectNames[161] = "objHeavyRain";
	global.__objectNames[162] = "objLightRain";
	global.__objectNames[163] = "objRain";
	global.__objectNames[164] = "objRainParentCollision";
	global.__objectNames[165] = "objSnow";
	global.__objectNames[166] = "objKnockedOut";
	global.__objectNames[167] = "objEnemyBurn";
	global.__objectNames[168] = "objBurningBody";
	global.__objectNames[169] = "objEDieBurn";
	global.__objectNames[170] = "objEnemySpawner";
	global.__objectNames[171] = "objMine";
	global.__objectNames[172] = "objEnemyIdleDrink";
	global.__objectNames[173] = "objEnemyIdleEatCandy";
	global.__objectNames[174] = "objEnemyIdleGuard";
	global.__objectNames[175] = "objEnemyIdleKnife";
	global.__objectNames[176] = "objEnemyIdleYawn";
	global.__objectNames[177] = "objEnemyIdleDrinkBeer";
	global.__objectNames[178] = "objEnemyIdlePee";
	global.__objectNames[179] = "objEnemyIdlePhone";
	global.__objectNames[180] = "objEnemyIdleSmokeMelee";
	global.__objectNames[181] = "objEnemyIdleSmokeSilencer";
	global.__objectNames[182] = "objEnemyDodger";
	global.__objectNames[183] = "objEnemyMeleePatrol";
	global.__objectNames[184] = "objEnemyMeleeRandom";
	global.__objectNames[185] = "objEnemyStaticMelee";
	global.__objectNames[186] = "enemyPatrol";
	global.__objectNames[187] = "enemyStatic";
	global.__objectNames[188] = "enemyRandom";
	global.__objectNames[189] = "enemyMeleeRandom";
	global.__objectNames[190] = "obj_AIwander";
	global.__objectNames[191] = "enemyCover";
	global.__objectNames[192] = "objEnemyGiveUp";
	global.__objectNames[193] = "efDesaturation";
	global.__objectNames[194] = "objConsole";
	global.__objectNames[195] = "objEffector";
	global.__objectNames[196] = "objGlareController";
	global.__objectNames[197] = "objSurfacer";
	global.__objectNames[198] = "WSOUND";
	global.__objectNames[199] = "efDirtyLens";
	global.__objectNames[200] = "objDrawRestart";
	global.__objectNames[201] = "objLevelComplete";
	global.__objectNames[202] = "objPoints";
	global.__objectNames[203] = "objThoughtFlash";
	global.__objectNames[204] = "objThoughtFlashDamaged";
	global.__objectNames[205] = "objDamageCounter";
	global.__objectNames[206] = "iconExecution";
	global.__objectNames[207] = "objMainMenu";
	global.__objectNames[208] = "objWave";
	global.__objectNames[209] = "objBird";
	global.__objectNames[210] = "objStar";
	global.__objectNames[211] = "objSeaGlimmer";
	global.__objectNames[212] = "objDisclaimer";
	global.__objectNames[213] = "iElisabeth";
	global.__objectNames[214] = "iFrancis";
	global.__objectNames[215] = "iJohanna";
	global.__objectNames[216] = "iJoseph";
	global.__objectNames[217] = "iMiller";
	global.__objectNames[218] = "iVeronika";
	global.__objectNames[219] = "iAmy";
	global.__objectNames[220] = "iDelilah";
	global.__objectNames[221] = "iJohn";
	global.__objectNames[222] = "iMariko";
	global.__objectNames[223] = "iNicole";
	global.__objectNames[224] = "iPierrette";
	global.__objectNames[225] = "iSimone";
	global.__objectNames[226] = "iThomas";
	global.__objectNames[227] = "iYsolda";
	global.__objectNames[228] = "mnCharacterSelect";
	global.__objectNames[229] = "objLevelSelect";
	global.__objectNames[230] = "objPause";
	global.__objectNames[231] = "objPauseMenuSplatter";
	global.__objectNames[232] = "objPauseMenuSplatterShot";
	global.__objectNames[233] = "mnPhone";
	global.__objectNames[234] = "objPhoneMessage";
	global.__objectNames[235] = "objPhoneNotification";
	global.__objectNames[236] = "objPhoneSendMail";
	global.__objectNames[237] = "objDirtySink";
	global.__objectNames[238] = "objDirtyToilet";
	global.__objectNames[239] = "objHotelSuiteTub";
	global.__objectNames[240] = "objShower";
	global.__objectNames[241] = "objSink";
	global.__objectNames[242] = "objLaundryMachine";
	global.__objectNames[243] = "objBathroomSinks";
	global.__objectNames[244] = "objToiletClean";
	global.__objectNames[245] = "objTowelDisposal";
	global.__objectNames[246] = "objTowels";
	global.__objectNames[247] = "objTub";
	global.__objectNames[248] = "objTubLawyer";
	global.__objectNames[249] = "objUrinal";
	global.__objectNames[250] = "objMakeupCabinet";
	global.__objectNames[251] = "objBedFlannel";
	global.__objectNames[252] = "objBed";
	global.__objectNames[253] = "objBedFancy";
	global.__objectNames[254] = "objArmChair";
	global.__objectNames[255] = "objLeatherCouchLarge";
	global.__objectNames[256] = "objCorporateCouch";
	global.__objectNames[257] = "objCorporateSofaLong";
	global.__objectNames[258] = "objCouchBeige";
	global.__objectNames[259] = "objCouchCushion";
	global.__objectNames[260] = "objCouchCushionGrey";
	global.__objectNames[261] = "objCouchGrey";
	global.__objectNames[262] = "objCouchLeatherBrown";
	global.__objectNames[263] = "objCouchLong";
	global.__objectNames[264] = "objCouchRipped";
	global.__objectNames[265] = "objHospitalChair";
	global.__objectNames[266] = "objJapaneseBench";
	global.__objectNames[267] = "objLeatherArmchair";
	global.__objectNames[268] = "objLeatherCouchAngled";
	global.__objectNames[269] = "objLeatherCouchBlack";
	global.__objectNames[270] = "objLeatherCouchL";
	global.__objectNames[271] = "objLeatherCouchV";
	global.__objectNames[272] = "objSaunaBench";
	global.__objectNames[273] = "objBelltowerSofa";
	global.__objectNames[274] = "objExplosiveBarrel";
	global.__objectNames[275] = "objACUnit";
	global.__objectNames[276] = "objAirDuct";
	global.__objectNames[277] = "objBarrel";
	global.__objectNames[278] = "objCementBags";
	global.__objectNames[279] = "objChemicalLab";
	global.__objectNames[280] = "objDrugMaterialShelf";
	global.__objectNames[281] = "objGateLocked";
	global.__objectNames[282] = "objGeneratorSmall";
	global.__objectNames[283] = "objLabCounter";
	global.__objectNames[284] = "objLabCounterBig";
	global.__objectNames[285] = "objLabIsland";
	global.__objectNames[286] = "objManholeNormal";
	global.__objectNames[287] = "objPipeLarge";
	global.__objectNames[288] = "objPipeSmall";
	global.__objectNames[289] = "objPortableGenerator";
	global.__objectNames[290] = "objPowerLines";
	global.__objectNames[291] = "objRoofVent";
	global.__objectNames[292] = "objSand";
	global.__objectNames[293] = "objSewerVentilation";
	global.__objectNames[294] = "objShippingCrateSmall";
	global.__objectNames[295] = "objToolTable";
	global.__objectNames[296] = "objTyre";
	global.__objectNames[297] = "objWarehouseCargoBig";
	global.__objectNames[298] = "objWarehouseCargoSmall";
	global.__objectNames[299] = "objWarehouseShelvesBoxesH";
	global.__objectNames[300] = "objWarehouseShelvesBoxesV";
	global.__objectNames[301] = "objWarehouseShelves";
	global.__objectNames[302] = "objWaterPipe";
	global.__objectNames[303] = "objWaterSource";
	global.__objectNames[304] = "objWoodenCrateLarge";
	global.__objectNames[305] = "objWoodenCrateLong";
	global.__objectNames[306] = "objWoodenCrateSmall";
	global.__objectNames[307] = "objWorkTable";
	global.__objectNames[308] = "objGarageDoor";
	global.__objectNames[309] = "objChairPlastic";
	global.__objectNames[310] = "objDrainageTub1";
	global.__objectNames[311] = "objDrainageTub2";
	global.__objectNames[312] = "objDrainageTub3";
	global.__objectNames[313] = "objDrainageWaste";
	global.__objectNames[314] = "objPlasticFloor";
	global.__objectNames[315] = "objBuffetLine";
	global.__objectNames[316] = "objBuffetPlates";
	global.__objectNames[317] = "objCoffeeTable";
	global.__objectNames[318] = "objCounter";
	global.__objectNames[319] = "objDoubleFridge";
	global.__objectNames[320] = "objDrinkTable";
	global.__objectNames[321] = "objFoodCounter";
	global.__objectNames[322] = "objFoodPreparationSupplies";
	global.__objectNames[323] = "objFoodTray";
	global.__objectNames[324] = "objFreezerSmall";
	global.__objectNames[325] = "objIndustrialKitchen";
	global.__objectNames[326] = "objKitchenCounter";
	global.__objectNames[327] = "objKitchenCupboard";
	global.__objectNames[328] = "objKitchenIsland";
	global.__objectNames[329] = "objKitchenIslandMarble";
	global.__objectNames[330] = "objKitchenSink";
	global.__objectNames[331] = "objKitchenWood";
	global.__objectNames[332] = "objMilitaryKitchen";
	global.__objectNames[333] = "objMilitaryTrays";
	global.__objectNames[334] = "objMinibar";
	global.__objectNames[335] = "objWineRacks";
	global.__objectNames[336] = "objPizza";
	global.__objectNames[337] = "objSingleFridge";
	global.__objectNames[338] = "objStove";
	global.__objectNames[339] = "objStoveSmall";
	global.__objectNames[340] = "objWashingMachine";
	global.__objectNames[341] = "objWoodenKitchenIsland";
	global.__objectNames[342] = "objKitchenAppliancesDark";
	global.__objectNames[343] = "objAlcohol";
	global.__objectNames[344] = "objBeerCooler";
	global.__objectNames[345] = "objCigarettes";
	global.__objectNames[346] = "objDrugCrate";
	global.__objectNames[347] = "objMarijuanaBig";
	global.__objectNames[348] = "objMarijuanaCrate";
	global.__objectNames[349] = "objMarijuanaCrop";
	global.__objectNames[350] = "objMarijuanaSmall";
	global.__objectNames[351] = "objMarijuanaTable";
	global.__objectNames[352] = "objBenchPress";
	global.__objectNames[353] = "objPunchingBag";
	global.__objectNames[354] = "objTreadMill";
	global.__objectNames[355] = "objWeightRack";
	global.__objectNames[356] = "objWeights";
	global.__objectNames[357] = "objAquarium";
	global.__objectNames[358] = "objBookshelfCheap";
	global.__objectNames[359] = "objBurningTrashcan";
	global.__objectNames[360] = "objBurntOutHoboFire";
	global.__objectNames[361] = "objCandleTableBurning";
	global.__objectNames[362] = "objCardboardBoxes";
	global.__objectNames[363] = "objCardboardBoxOpened";
	global.__objectNames[364] = "objChainFenceH";
	global.__objectNames[365] = "objChair";
	global.__objectNames[366] = "objSafeLarge";
	global.__objectNames[367] = "objCleaningCart";
	global.__objectNames[368] = "objClosetGrey";
	global.__objectNames[369] = "objClosetHangerLong";
	global.__objectNames[370] = "objClothesHanger";
	global.__objectNames[371] = "objClothesHangerCircle";
	global.__objectNames[372] = "objClothesline";
	global.__objectNames[373] = "objDoorMatLawyer";
	global.__objectNames[374] = "objDoormatTiny";
	global.__objectNames[375] = "objDumpster";
	global.__objectNames[376] = "objFirePlace";
	global.__objectNames[377] = "objFormsFloor";
	global.__objectNames[378] = "objFuseBox";
	global.__objectNames[379] = "objGrandPiano";
	global.__objectNames[380] = "objHearth";
	global.__objectNames[381] = "objHearthBucket";
	global.__objectNames[382] = "objHospitalBed";
	global.__objectNames[383] = "objHotelClosetV";
	global.__objectNames[384] = "objHotelFootStool";
	global.__objectNames[385] = "objIrori";
	global.__objectNames[386] = "objJanitorBucket";
	global.__objectNames[387] = "objLamp";
	global.__objectNames[388] = "objLaundryBasket";
	global.__objectNames[389] = "objLuggage";
	global.__objectNames[390] = "objMassageTableHotel";
	global.__objectNames[391] = "objMassageTools";
	global.__objectNames[392] = "objMetalDetector";
	global.__objectNames[393] = "objMilkCarton";
	global.__objectNames[394] = "objNewspaperStand";
	global.__objectNames[395] = "objPaintingWallMetal";
	global.__objectNames[396] = "objPaintingWallWood";
	global.__objectNames[397] = "objPants";
	global.__objectNames[398] = "objPaperFloorMess";
	global.__objectNames[399] = "objPaperStack";
	global.__objectNames[400] = "objPavementDrain";
	global.__objectNames[401] = "objPhoneRecorder1";
	global.__objectNames[402] = "objPhoneRecorder2";
	global.__objectNames[403] = "objPorchBenchDecrepit";
	global.__objectNames[404] = "objPuddle";
	global.__objectNames[405] = "objRake";
	global.__objectNames[406] = "objShirts";
	global.__objectNames[407] = "objShoes";
	global.__objectNames[408] = "objShojiH";
	global.__objectNames[409] = "objShojiOpenH";
	global.__objectNames[410] = "objShojiOpenV";
	global.__objectNames[411] = "objShojiV";
	global.__objectNames[412] = "objStreetLightBase";
	global.__objectNames[413] = "objStyrofoam";
	global.__objectNames[414] = "objSurveillanceBank";
	global.__objectNames[415] = "objSurveillanceCamera";
	global.__objectNames[416] = "objSurveillancePanel";
	global.__objectNames[417] = "objTrashbag";
	global.__objectNames[418] = "objTrashbagOpen";
	global.__objectNames[419] = "objTrashbin";
	global.__objectNames[420] = "objTrashBinLarge";
	global.__objectNames[421] = "objTrashBinSquare";
	global.__objectNames[422] = "objTrashFood";
	global.__objectNames[423] = "objTVFlatScreen";
	global.__objectNames[424] = "objTVFlatScreenLarge";
	global.__objectNames[425] = "objTVWall";
	global.__objectNames[426] = "objWaterCooler";
	global.__objectNames[427] = "objWetFloorWarning";
	global.__objectNames[428] = "objWetSpot";
	global.__objectNames[429] = "objXray";
	global.__objectNames[430] = "objFrostedGlassPanel";
	global.__objectNames[431] = "objShootingTarget";
	global.__objectNames[432] = "objOrientalRug1";
	global.__objectNames[433] = "objOrientalRug2";
	global.__objectNames[434] = "objOrientalRug3";
	global.__objectNames[435] = "objBookshelfWood";
	global.__objectNames[436] = "objShelfWood";
	global.__objectNames[437] = "objShelfWoodPapers";
	global.__objectNames[438] = "objLocker";
	global.__objectNames[439] = "objClosetWood";
	global.__objectNames[440] = "objDataArchive";
	global.__objectNames[441] = "objDataRecorder";
	global.__objectNames[442] = "objBelltowerDeskLarge";
	global.__objectNames[443] = "objBelltowerEntryDesk";
	global.__objectNames[444] = "objBelltowerBigTable";
	global.__objectNames[445] = "objDeskBase";
	global.__objectNames[446] = "objFancyDesk";
	global.__objectNames[447] = "objJunesRegister";
	global.__objectNames[448] = "objKotatsu";
	global.__objectNames[449] = "objLunchTable";
	global.__objectNames[450] = "objLunchTableChair";
	global.__objectNames[451] = "objLunchTableGang";
	global.__objectNames[452] = "objLunchTableLongSpecial";
	global.__objectNames[453] = "objLunchTableLongV";
	global.__objectNames[454] = "objLunchTableSmall";
	global.__objectNames[455] = "objMassageReception";
	global.__objectNames[456] = "objMilitaryDiningTable";
	global.__objectNames[457] = "objPhoneTable";
	global.__objectNames[458] = "objBelltowerDeskH";
	global.__objectNames[459] = "objBelltowerDeskV";
	global.__objectNames[460] = "objSmallTable";
	global.__objectNames[461] = "objDiningTableWood";
	global.__objectNames[462] = "objSquareTableWood";
	global.__objectNames[463] = "objTable";
	global.__objectNames[464] = "objTableBroken";
	global.__objectNames[465] = "objTableCircular";
	global.__objectNames[466] = "objTableGambling";
	global.__objectNames[467] = "objTableGang";
	global.__objectNames[468] = "objTableGangMessy";
	global.__objectNames[469] = "objTableSquareLight";
	global.__objectNames[470] = "objTableGlass";
	global.__objectNames[471] = "objTableTVWhite";
	global.__objectNames[472] = "objMuleTruck";
	global.__objectNames[473] = "objVanUnload";
	global.__objectNames[474] = "objUtilityVan";
	global.__objectNames[475] = "objPickupTruck";
	global.__objectNames[476] = "objBushCorner";
	global.__objectNames[477] = "objBushFlowers";
	global.__objectNames[478] = "objBushLarge";
	global.__objectNames[479] = "objBushSmall";
	global.__objectNames[480] = "objBushSnowyLarge";
	global.__objectNames[481] = "objBushSnowySmall";
	global.__objectNames[482] = "objHedgeH";
	global.__objectNames[483] = "objHedgeV";
	global.__objectNames[484] = "objNaturalWaterfallSmall";
	global.__objectNames[485] = "objPalmBroken";
	global.__objectNames[486] = "objPalmDay";
	global.__objectNames[487] = "objPalmNight";
	global.__objectNames[488] = "objPalmTree";
	global.__objectNames[489] = "objPalmTreeLarge";
	global.__objectNames[490] = "objPalmTreeSmall";
	global.__objectNames[491] = "objPlantDead";
	global.__objectNames[492] = "objPlanter1";
	global.__objectNames[493] = "objPlanter2";
	global.__objectNames[494] = "objPlantHolderWall";
	global.__objectNames[495] = "objPlantSmall";
	global.__objectNames[496] = "objPlantSmallSnowy";
	global.__objectNames[497] = "objPlantsNature";
	global.__objectNames[498] = "objPlayerTree";
	global.__objectNames[499] = "objRocks";
	global.__objectNames[500] = "objSakuraPetalsGround";
	global.__objectNames[501] = "objLeavesScattered";
	global.__objectNames[502] = "objSakuraSmall";
	global.__objectNames[503] = "objSakuraTree";
	global.__objectNames[504] = "objTreeDead";
	global.__objectNames[505] = "objTreeForestNight";
	global.__objectNames[506] = "objTreeForestNormal";
	global.__objectNames[507] = "objTreeForestSnowy";
	global.__objectNames[508] = "objTreeMassive";
	global.__objectNames[509] = "objTreeNormal";
	global.__objectNames[510] = "objTreePot";
	global.__objectNames[511] = "objTreeSmall";
	global.__objectNames[512] = "objWoodenTrellis";
	global.__objectNames[513] = "objWoodenTrellisLong";
	global.__objectNames[514] = "objDirtRoad";
	global.__objectNames[515] = "objFirePit";
	global.__objectNames[516] = "objLog";
	global.__objectNames[517] = "objBarbedWire";
	global.__objectNames[518] = "objTent";
	global.__objectNames[519] = "objHose";
	global.__objectNames[520] = "objRiverFrozen";
	global.__objectNames[521] = "objBarBooth";
	global.__objectNames[522] = "objBarFancy";
	global.__objectNames[523] = "objBarFancySmall";
	global.__objectNames[524] = "objBarLights";
	global.__objectNames[525] = "objBarRegister";
	global.__objectNames[526] = "objBarShelf";
	global.__objectNames[527] = "objBarShelfWood";
	global.__objectNames[528] = "objBarSmallBlack";
	global.__objectNames[529] = "objBarStage";
	global.__objectNames[530] = "objBarStoolBlack";
	global.__objectNames[531] = "objBarStoolEquinox";
	global.__objectNames[532] = "objBarStoolLeather";
	global.__objectNames[533] = "objBarStoolWhite";
	global.__objectNames[534] = "objBarTableBlack";
	global.__objectNames[535] = "objBarTableWood";
	global.__objectNames[536] = "objBarWood";
	global.__objectNames[537] = "objBarShelfWoodLong";
	global.__objectNames[538] = "objDinerBuffet";
	global.__objectNames[539] = "objDinerChair";
	global.__objectNames[540] = "objDinerCoffeeTable";
	global.__objectNames[541] = "objDinerCounterLarge";
	global.__objectNames[542] = "objDinerCup";
	global.__objectNames[543] = "objDinerFoodCounter";
	global.__objectNames[544] = "objDinerGrill";
	global.__objectNames[545] = "objDinerSink";
	global.__objectNames[546] = "objDinerSodaFountain";
	global.__objectNames[547] = "objDinerTable";
	global.__objectNames[548] = "objDinerWindowH";
	global.__objectNames[549] = "objDinerWindowV";
	global.__objectNames[550] = "objBannerV";
	global.__objectNames[551] = "objBeadedArmchair";
	global.__objectNames[552] = "objBonsaiTreeLarge";
	global.__objectNames[553] = "objBuddha";
	global.__objectNames[554] = "objChineseBar";
	global.__objectNames[555] = "objChineseBarShelf";
	global.__objectNames[556] = "objChineseFishtank";
	global.__objectNames[557] = "objChineseFoodDisplay";
	global.__objectNames[558] = "objChineseLightBlue";
	global.__objectNames[559] = "objChineseLightOrange";
	global.__objectNames[560] = "objChineseLightPink";
	global.__objectNames[561] = "objChineseLightRed";
	global.__objectNames[562] = "objChinesePlantSmall";
	global.__objectNames[563] = "objChineseStatue";
	global.__objectNames[564] = "objFoodPrepTable";
	global.__objectNames[565] = "objFryingKitchen";
	global.__objectNames[566] = "objGoldenCat";
	global.__objectNames[567] = "objGoldenDragon";
	global.__objectNames[568] = "objGunsmithDesk";
	global.__objectNames[569] = "objHighballSign";
	global.__objectNames[570] = "objKitchenBenchGunsmith";
	global.__objectNames[571] = "objKitchenLightQuad";
	global.__objectNames[572] = "objNoodleTableH";
	global.__objectNames[573] = "objPantherStatue";
	global.__objectNames[574] = "objRailBar";
	global.__objectNames[575] = "objRegisterBrown";
	global.__objectNames[576] = "objTableGunSmith";
	global.__objectNames[577] = "objTargetPractice";
	global.__objectNames[578] = "objTVParty1";
	global.__objectNames[579] = "objTVParty3";
	global.__objectNames[580] = "objWokKitchen";
	global.__objectNames[581] = "objMetroCarScene";
	global.__objectNames[582] = "objMetroCarWall";
	global.__objectNames[583] = "objMetroCarWindowH";
	global.__objectNames[584] = "objMetroLeanHandle";
	global.__objectNames[585] = "objMetroSeatsDouble";
	global.__objectNames[586] = "objMetroSeatsLine";
	global.__objectNames[587] = "objMetroStandHandleDown";
	global.__objectNames[588] = "objMetroStandHandleUp";
	global.__objectNames[589] = "objSubwayBenchH";
	global.__objectNames[590] = "objSubwayBenchV";
	global.__objectNames[591] = "objSubwayBillboard";
	global.__objectNames[592] = "objSubwayDoor";
	global.__objectNames[593] = "objSubwayGate";
	global.__objectNames[594] = "objSubwayGateLocked";
	global.__objectNames[595] = "objSubwayLight";
	global.__objectNames[596] = "objSubwayLightV";
	global.__objectNames[597] = "objSubwayMap";
	global.__objectNames[598] = "objSubwayPole";
	global.__objectNames[599] = "objSubwayReception";
	global.__objectNames[600] = "objSubwayTimeDisplay";
	global.__objectNames[601] = "objExecutiveTable";
	global.__objectNames[602] = "objComputerMonitor";
	global.__objectNames[603] = "objComputerParts";
	global.__objectNames[604] = "objComputerPartsBig";
	global.__objectNames[605] = "objConferenceTableDark";
	global.__objectNames[606] = "objConferenceTableLight";
	global.__objectNames[607] = "objCopyMachine";
	global.__objectNames[608] = "objCorporateDoors";
	global.__objectNames[609] = "objCorporateReceptionLight";
	global.__objectNames[610] = "objFileCabinet";
	global.__objectNames[611] = "objLaptop";
	global.__objectNames[612] = "objModernArt";
	global.__objectNames[613] = "objOfficeBarMassive";
	global.__objectNames[614] = "objOfficeDrapes";
	global.__objectNames[615] = "objOfficeFountainLarge";
	global.__objectNames[616] = "objOfficeFountainMedium";
	global.__objectNames[617] = "objOfficeFountainSmall1";
	global.__objectNames[618] = "objOfficeFountainSmall2";
	global.__objectNames[619] = "objOfficePlant";
	global.__objectNames[620] = "objOfficePlantSmall";
	global.__objectNames[621] = "objOfficeReceptionTable";
	global.__objectNames[622] = "objOfficeTableBig";
	global.__objectNames[623] = "objOfficeTableCircular";
	global.__objectNames[624] = "objOfficeTableSmall";
	global.__objectNames[625] = "objRollingChairOffice";
	global.__objectNames[626] = "objRollingChairPolice";
	global.__objectNames[627] = "objWhiteBoard";
	global.__objectNames[628] = "objWhiteBoardLarge";
	global.__objectNames[629] = "objBoardwalkOcean";
	global.__objectNames[630] = "objCreateWater";
	global.__objectNames[631] = "objFishWater";
	global.__objectNames[632] = "objLeafWater";
	global.__objectNames[633] = "objOceanFog";
	global.__objectNames[634] = "objRailV";
	global.__objectNames[635] = "objRippleLake";
	global.__objectNames[636] = "objWaterSurface";
	global.__objectNames[637] = "objWaterTile";
	global.__objectNames[638] = "objWoodenBench";
	global.__objectNames[639] = "objBoatBridge";
	global.__objectNames[640] = "objBoatPool";
	global.__objectNames[641] = "objLifePreserver";
	global.__objectNames[642] = "objSunchair";
	global.__objectNames[643] = "objParasol";
	global.__objectNames[644] = "objCommsTable";
	global.__objectNames[645] = "objAmmoBox";
	global.__objectNames[646] = "objSupplyBox";
	global.__objectNames[647] = "objWeaponSpawn";
	global.__objectNames[648] = "objAxeWall";
	global.__objectNames[649] = "objGrenadeSpawn";
	global.__objectNames[650] = "objKatanaWall";
	global.__objectNames[651] = "objToolbox";
	global.__objectNames[652] = "objUtilityClosetMetal";
	global.__objectNames[653] = "objVendingMachine";
	global.__objectNames[654] = "objSodaCan";
	global.__objectNames[655] = "objLightBarOrange";
	global.__objectNames[656] = "objLightBarWhite";
	global.__objectNames[657] = "objNeonSignRed";
	global.__objectNames[658] = "objOfficeLightDown";
	global.__objectNames[659] = "objOfficeLightLeft";
	global.__objectNames[660] = "objOfficeLightRight";
	global.__objectNames[661] = "objOfficeLightUp";
	global.__objectNames[662] = "objStreetLight";
	global.__objectNames[663] = "objWallLamp";
	global.__objectNames[664] = "objStreetLightWhite";
	global.__objectNames[665] = "objFloorLamp";
	global.__objectNames[666] = "objStreetLampAmber";
	global.__objectNames[667] = "objLFGlowOrange";
	global.__objectNames[668] = "objLFTailOrange";
	global.__objectNames[669] = "objLightMonitor";
	global.__objectNames[670] = "objLightTV";
	global.__objectNames[671] = "objMetroLight";
	global.__objectNames[672] = "objMuzzleLight";
	global.__objectNames[673] = "objVMAqua";
	global.__objectNames[674] = "objVMGreen";
	global.__objectNames[675] = "objVMOrange";
	global.__objectNames[676] = "objVMPink";
	global.__objectNames[677] = "objSAWhite";
	global.__objectNames[678] = "objSAAmber";
	global.__objectNames[679] = "objSAGreen";
	global.__objectNames[680] = "objSAOrange";
	global.__objectNames[681] = "objSAPink";
	global.__objectNames[682] = "objSARed";
	global.__objectNames[683] = "objSAAqua";
	global.__objectNames[684] = "objPlayerCar";
	global.__objectNames[685] = "objPlayerCarFloor";
	global.__objectNames[686] = "objPlayerCarRoof";
	global.__objectNames[687] = "objPlayerCarTrunk";
	global.__objectNames[688] = "objPlayerCarTrunkInterior";
	global.__objectNames[689] = "objPAttackKnee";
	global.__objectNames[690] = "objPAttackThroat";
	global.__objectNames[691] = "objPAxeKill";
	global.__objectNames[692] = "objPBluntKill";
	global.__objectNames[693] = "objPBoilingPotKill";
	global.__objectNames[694] = "objPBottleBrokenKill";
	global.__objectNames[695] = "objPBottleKill";
	global.__objectNames[696] = "objPBrickKill";
	global.__objectNames[697] = "objPBrokenPoolKill";
	global.__objectNames[698] = "objPChainsawKill1";
	global.__objectNames[699] = "objPChainsawKill2";
	global.__objectNames[700] = "objPDrillKill";
	global.__objectNames[701] = "objPKill9mm";
	global.__objectNames[702] = "objPKillAJM";
	global.__objectNames[703] = "objPKillAK";
	global.__objectNames[704] = "objPKillBeretta";
	global.__objectNames[705] = "objPKillChainsawLean";
	global.__objectNames[706] = "objPKillCleaver";
	global.__objectNames[707] = "objPKillClub";
	global.__objectNames[708] = "objPKillDesertEagle";
	global.__objectNames[709] = "objPKillFAL";
	global.__objectNames[710] = "objPKillFAMAE";
	global.__objectNames[711] = "objPKillFat";
	global.__objectNames[712] = "objPKillHammer";
	global.__objectNames[713] = "objPKillHeadRip";
	global.__objectNames[714] = "objPKillHK417";
	global.__objectNames[715] = "objPKillIngram";
	global.__objectNames[716] = "objPKillKatana";
	global.__objectNames[717] = "objPKillKitchenKnife";
	global.__objectNames[718] = "objPKillKnife";
	global.__objectNames[719] = "objPKillKnifeStab";
	global.__objectNames[720] = "objPKillLean";
	global.__objectNames[721] = "objPKillLeanNonlethal";
	global.__objectNames[722] = "objPKillMachete";
	global.__objectNames[723] = "objPKillMacheteSlash";
	global.__objectNames[724] = "objPKillMagnum";
	global.__objectNames[725] = "objPKillMP5";
	global.__objectNames[726] = "objPKillNailgun";
	global.__objectNames[727] = "objPKillNeckSnap";
	global.__objectNames[728] = "objPKillP90";
	global.__objectNames[729] = "objPKillPipe";
	global.__objectNames[730] = "objPKillPunch";
	global.__objectNames[731] = "objPKillShotgun";
	global.__objectNames[732] = "objPKillSilencer";
	global.__objectNames[733] = "objPKillStomp";
	global.__objectNames[734] = "objPKillThompson";
	global.__objectNames[735] = "objPKillUzi";
	global.__objectNames[736] = "objPKillWrench";
	global.__objectNames[737] = "objPMercyKillSnap";
	global.__objectNames[738] = "objPMercyKillStomp";
	global.__objectNames[739] = "objPPoolKill";
	global.__objectNames[740] = "objPScrewdriverKill";
	global.__objectNames[741] = "objPSkateboardKill";
	global.__objectNames[742] = "objPSledgeKill";
	global.__objectNames[743] = "objThomasAttackKnee";
	global.__objectNames[744] = "objPlayerDead";
	global.__objectNames[745] = "objPlayer";
	global.__objectNames[746] = "objHealthPickup";
	global.__objectNames[747] = "maskShield";
	global.__objectNames[748] = "objPierretteShield";
	global.__objectNames[749] = "objDoorH";
	global.__objectNames[750] = "objDoorH2";
	global.__objectNames[751] = "objDoorV";
	global.__objectNames[752] = "objDoorV2";
	global.__objectNames[753] = "objSlidingDoorH";
	global.__objectNames[754] = "objSlidingDoorsDoubleH";
	global.__objectNames[755] = "objSlidingDoorsDoubleV";
	global.__objectNames[756] = "objSlidingDoorV";
	global.__objectNames[757] = "objCorporateDoorsH";
	global.__objectNames[758] = "objTeleporter";
	global.__objectNames[759] = "objConcreteBlock";
	global.__objectNames[760] = "objWallBrickH";
	global.__objectNames[761] = "objWallBrickV";
	global.__objectNames[762] = "objWallHeavyV";
	global.__objectNames[763] = "objWallHeavyH";
	global.__objectNames[764] = "objWallCorner";
	global.__objectNames[765] = "objWallWoodH";
	global.__objectNames[766] = "objWallWoodV";
	global.__objectNames[767] = "objFenceV";
	global.__objectNames[768] = "objFenceH";
	global.__objectNames[769] = "objInvisibleBoundary";
	global.__objectNames[770] = "objRenovationWallH";
	global.__objectNames[771] = "objRenovationWallV";
	global.__objectNames[772] = "objBrokenWindowH";
	global.__objectNames[773] = "objBrokenWindowV";
	global.__objectNames[774] = "objGlassPanelH";
	global.__objectNames[775] = "objGlassPanelHBroken";
	global.__objectNames[776] = "objGlassPanelV";
	global.__objectNames[777] = "objGlassPanelVBroken";
	global.__objectNames[778] = "objWallWindow";
	global.__objectNames[779] = "objWindowH";
	global.__objectNames[780] = "objWindowV";
	global.__objectNames[781] = "objWindowExplodeH";
	global.__objectNames[782] = "objWindowExplodeV";
	global.__objectNames[783] = "objGlassWall";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
