/// scrGetWeapon(index)

// Drop current weapon.
with objPlayer {
    lastweapon = scrCurrentWeaponExt(objPlayer.sprite_index)
    lastammo = ammo
    scrThrowWeapon()
}

sound_ps(sndPickUpWeapon)
if image_index=0 objPlayer.sprite_index=sprPWalkHK417
if image_index=1 objPlayer.sprite_index=sprPWalkShotgun
if image_index=2 objPlayer.sprite_index=sprPWalkClub
if image_index=3 objPlayer.sprite_index=sprPWalkPipe
if image_index=4 objPlayer.sprite_index=sprPWalkBat
if image_index=5 objPlayer.sprite_index=sprPWalkKnife
if image_index=6 objPlayer.sprite_index=sprPWalkDoubleBarrel
if image_index=7 objPlayer.sprite_index=sprPWalkSilencer
if image_index=8 objPlayer.sprite_index=sprPWalkKatana
if image_index=9 objPlayer.sprite_index=sprPWalkUzi
if image_index=10 objPlayer.sprite_index=sprPWalkMagnum
if image_index=11 objPlayer.sprite_index=sprPWalkScorpion
if image_index=12 objPlayer.sprite_index=sprPWalkMP5
if image_index=13 objPlayer.sprite_index=sprPWalkPool
if image_index=14 objPlayer.sprite_index=sprPWalkM16
if image_index=15 objPlayer.sprite_index=sprPWalkAxe
if image_index=16 objPlayer.sprite_index=sprPWalkNightStick
if image_index=17 objPlayer.sprite_index=sprPWalkCrowbar
if image_index=18 objPlayer.sprite_index=sprPWalkMachete
if image_index=19 objPlayer.sprite_index=sprPWalkSledgeHammer
if image_index=20 objPlayer.sprite_index=sprPWalkTrophy
if image_index=21 objPlayer.sprite_index=sprPWalkDrill
if image_index=22 objPlayer.sprite_index=sprPWalkPan
if image_index=23 objPlayer.sprite_index=sprPWalkBoilingPot
if image_index=24 objPlayer.sprite_index=sprPWalkPot
if image_index=25 objPlayer.sprite_index=sprPWalkIngram
if image_index=26 objPlayer.sprite_index=sprPWalkAK
if image_index=27 objPlayer.sprite_index=sprPWalkHandgun
if image_index=28 objPlayer.sprite_index=sprPWalkFlamethrower
if image_index=29 objPlayer.sprite_index=sprPWalkSniper
if image_index=30 objPlayer.sprite_index=sprPWalkSilencedShotgun
if image_index=31 objPlayer.sprite_index=sprPWalkChainsaw
if image_index=32 objPlayer.sprite_index=sprPWalkSuppressedMG
if image_index=33 objPlayer.sprite_index=sprPWalkNailGun
if image_index=34 objPlayer.sprite_index=sprPWalkChain
if image_index=35 objPlayer.sprite_index=sprPWalkCleaver
if image_index=36 objPlayer.sprite_index=sprPWalkFlareGun
if image_index=37 objPlayer.sprite_index=sprPWalkSkateboard
if image_index=38 { objPlayer.sprite_index=sprPWalkRealizer sound_ps(sndRealizerPickUp) }
if image_index=39 objPlayer.sprite_index=sprPWalkArm
if image_index=40 objPlayer.sprite_index=sprPWalkBust
if image_index=41 objPlayer.sprite_index=sprPWalkThompson
if image_index=42 objPlayer.sprite_index=sprPWalkLMG
if image_index=43 objPlayer.sprite_index=sprPWalkCrossbow
if image_index=44 objPlayer.sprite_index=sprPWalkGuitar
if image_index=45 objPlayer.sprite_index=sprPWalkGarand
if image_index=46 objPlayer.sprite_index=sprPWalkScythe
if image_index=47 objPlayer.sprite_index=sprPWalkAutoShotgun
if image_index=49 objPlayer.sprite_index=sprPWalkWA2000
if image_index=50 objPlayer.sprite_index=sprPWalkHammer
if image_index=51 objPlayer.sprite_index=sprPWalkWrench
if image_index=52 objPlayer.sprite_index=sprPWalkDesertEagle
if image_index=53 objPlayer.sprite_index=sprPWalkCircularSaw
if image_index=54 objPlayer.sprite_index=sprPWalkKSG
if image_index=55 objPlayer.sprite_index=sprPWalkFMG
//if image_index=56 objPlayer.sprite_index=sprPWalkHatchet
if image_index=57 objPlayer.sprite_index=sprPWalkAJM
if image_index=58 objPlayer.sprite_index=sprPWalkMultiplas
if image_index=59 objPlayer.sprite_index=sprPWalkDisruptor
if image_index=60 objPlayer.sprite_index=sprPWalkM79
if image_index=61 objPlayer.sprite_index=sprPWalkMGL
if image_index=62 objPlayer.sprite_index=sprPWalkMauser
if image_index=63 objPlayer.sprite_index=sprPWalkRPG
if image_index=64 { objPlayer.sprite_index=sprPWalkPatriot sound_ps(sndPatriotPickUp) }
if image_index=65 objPlayer.sprite_index=sprPWalkBong
//if image_index=66 objPlayer.sprite_index=sprPWalkBattleAxe
if image_index=67 objPlayer.sprite_index=sprPWalkShovel
//if image_index=68 objPlayer.sprite_index=sprPWalkSAA
if image_index=69 objPlayer.sprite_index=sprPWalkSawedOff
if image_index=70 objPlayer.sprite_index=sprPWalkBottle
if image_index=71 objPlayer.sprite_index=sprPWalkIthaca
if image_index=72 objPlayer.sprite_index=sprPWalkHysteria
if image_index=73 objPlayer.sprite_index=sprPWalkBow
if image_index=74 objPlayer.sprite_index=sprPWalkBrick
if image_index=75 objPlayer.sprite_index=sprPWalkBigPipe
if image_index=76 objPlayer.sprite_index=sprPWalkFAMAE
if image_index=77 objPlayer.sprite_index=sprPWalkFAL
if image_index=78 objPlayer.sprite_index=sprPWalk1887
if image_index=79 objPlayer.sprite_index=sprPWalkHalberd
if image_index=80 objPlayer.sprite_index=sprPWalkLeviathan
if image_index=81 objPlayer.sprite_index=sprPWalkLongSword
if image_index=82 objPlayer.sprite_index=sprPWalkMace
//if image_index=83 objPlayer.sprite_index=sprPWalkExtinguisher
if image_index=84 objPlayer.sprite_index=sprPWalkScrewdriver
//if image_index=85 objPlayer.sprite_index=
if image_index=86 objPlayer.sprite_index=sprPWalkBag
//if image_index=87 objPlayer.sprite_index=sprPWalkStunBaton
//if image_index=88 objPlayer.sprite_index=sprPWalkFish
//if image_index=89 objPlayer.sprite_index=sprPWalkPitchfork
//if image_index=90 objPlayer.sprite_index=sprPWalkSign
//if image_index=91 objPlayer.sprite_index=sprPWalkShears
//if image_index=92 objPlayer.sprite_index=sprPWalkAcidSoaker
if image_index=93 objPlayer.sprite_index=sprPWalkScissors
//if image_index=94 objPlayer.sprite_index=sprPWalkWaterPistol
//if image_index=95 objPlayer.sprite_index=sprPWalkWaterShotgun
//if image_index=96 objPlayer.sprite_index=sprPWalkWaterLauncher
//if image_index=97 objPlayer.sprite_index=sprPWalkWaterSniper
if image_index=98 objPlayer.sprite_index=sprPWalkWaterCannon
